version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "amplify-utils"
s3_bucket = "elrincondelsanchez"
s3_prefix = "lambda/layers/amplify-utils"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
