AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: amplify-utils
      ContentUri: ./layer/
      CompatibleRuntimes:
      - python3.8
      RetentionPolicy: Retain
